# -*- coding: utf-8 -*-
"""One-shot helper: fill ar.po from relayruntime.pot (Phase 3)."""
from __future__ import annotations

import re
from pathlib import Path

import polib

POT = Path(__file__).resolve().parents[1] / "relayruntime" / "i18n" / "relayruntime.pot"
PO = POT.with_name("ar.po")

# Operational / runtime labels and tokens — intentionally English (empty msgstr).
KEEP_ENGLISH = {
    "API Message ID",
    "API Response",
    "API Response Body",
    "API URL",
    "API Version",
    "Access Token",
    "Active Execution",
    "Attempt Kind",
    "Business Account ID",
    "Capabilities (JSON)",
    "Custom Internal API",
    "Duplicate message log idempotency key.",
    "Evolution API",
    "Exception Type",
    "Exec %(campaign)s #%(n)s",
    "Execution Count",
    "Execution Finished",
    "Execution Lock Expires",
    "Execution Started",
    "Execution Token",
    "Execution UUID",
    "Execution UUID must be unique.",
    "Executor",
    "Fallback Provider Config",
    "Force Auth Failure on Test",
    "Force Disconnect on Test",
    "Green API",
    "Gupshup",
    "Idempotency Key",
    "Instance ID",
    "Last Heartbeat",
    "Last Recipient Index",
    "Lease Expires",
    "Lease Token",
    "Log Count",
    "Log File Path",
    "Meta WhatsApp Cloud API",
    "Mock Provider (Test Mode)",
    "Mock simulation rate \"%(field)s\" must be between 0 and 100.",
    "Outbound Intent At",
    "Parent Execution",
    "Phone Number ID",
    "Processing Duration (s)",
    "Processing State",
    "Provider Debug Info",
    "Provider Implemented",
    "Provider Name",
    "Provider Version",
    "Reconciled",
    "Related Model",
    "Related Record ID",
    "Retry Fingerprint",
    "Retryable",
    "Simulated authentication failure (config flag).",
    "Simulated provider disconnect (config flag).",
    "State",
    "Traceback Summary",
    "Twilio WhatsApp",
    "UltraMsg",
    "Webhook Secret",
    "WhatsApp Bulk Execution Attempt",
    "WhatsApp Product Selection Line",
    "WhatsApp Product Selection Wizard",
    "WhatsApp Product Selection Wizard",
    "Send WhatsApp Bulk Wizard",
    "Send WhatsApp Message Wizard",
    "campaign_id",
    "whatsapp_campaign_id",
    "https://api.green-api.com",
    "Use these normalized numbers on contacts to force specific outcomes:\n"
    "                                    201000000000 invalid · 201111111111 auth · 201222222222 disconnect ·\n"
    "                                    201333333333 timeout · 201444444444 rate limit · 201555555555 malformed ·\n"
    "                                    201666666666 attachment fail",
    "Deprecated alias; use current_recipient_id.",
    "Green API instance id.",
    "Meta / business WABA id.",
    "Meta Cloud phone number id.",
    "Provider API version (e.g. v18.0 for Meta).",
    "Secret for webhook signature verification.",
    "When delivery was committed in DB before calling the provider.",
    "When the bulk sender finished or was interrupted.",
    "When the bulk sender started processing recipients.",
    "Previous execution this retry attempt continues from.",
    "Reserved for future failover support. Not active yet.",
    "Connection test always fails with authentication error.",
    "Connection test always fails with disconnect error.",
    "Pause before each simulated API call (stress-test delays).",
    "Random outcome weight for generic API failures.",
    "Random outcome weight for simulated rate limits.",
    "Random outcome weight for simulated timeouts.",
    "Random outcome weight for successful sends (0–100).",
    "Extra failure chance on media sends only (0–100).",
}

# Exact Arabic translations (user-facing UX).
TRANSLATIONS = {
    "%(field)s must be between 0 and 100.": "يجب أن يكون %(field)s بين 0 و 100.",
    "%(processed)s / %(total)s processed · %(remaining)s remaining": "%(processed)s / %(total)s مُعالَج · %(remaining)s متبقٍ",
    "(attachment)": "(مرفق)",
    "(attachments only)": "(مرفقات فقط)",
    "A retry campaign for the same parent and recipient set already exists.": "توجد بالفعل حملة إعادة محاولة لنفس الحملة الأصلية ومجموعة المستلمين.",
    "Active": "نشط",
    "Add at least one product line.": "أضف سطر منتج واحدًا على الأقل.",
    "Add sale description under each product line in the catalog text.": "أضف وصف البيع تحت كل منتج في نص الكتالوج.",
    "Advanced": "متقدم",
    "All Logs": "كل السجلات",
    "Archived": "مؤرشف",
    "Attachment": "مرفق",
    "Attachment \"%(name)s\" has unsupported type \"%(mime)s\".": "المرفق \"%(name)s\" من نوع غير مدعوم \"%(mime)s\".",
    "Attachment \"%(name)s\" is too large (%(size).2f MB). Maximum allowed: %(max)s MB.": "المرفق \"%(name)s\" كبير جدًا (%(size).2f MB). الحد الأقصى: %(max)s MB.",
    "Attachment Count": "عدد المرفقات",
    "Attachment Failure Rate %": "نسبة فشل المرفقات %",
    "Attachment Filename": "اسم ملف المرفق",
    "Attachment failure rate cannot be negative.": "لا يمكن أن تكون نسبة فشل المرفقات سالبة.",
    "Attachments": "المرفقات",
    "Attachments Sent": "مرفقات مُرسلة",
    "Attachments are not allowed.": "المرفقات غير مسموحة.",
    "Base URL of your WhatsApp API provider.": "عنوان URL الأساسي لمزود واتساب.",
    "Bulk %s": "جماعي %s",
    "Bulk Campaign": "حملة جماعية",
    "Bulk Campaigns": "الحملات الجماعية",
    "Bulk send finished: %(total)s total, %(sent)s sent, %(failed)s failed, %(skipped)s skipped, %(cooldowns)s cooldown(s), %(attachments)s attachment(s) sent.": "اكتمل الإرسال الجماعي: %(total)s إجمالي، %(sent)s مُرسل، %(failed)s فشل، %(skipped)s تم تخطيه، %(cooldowns)s فترة/فترات تهدئة، %(attachments)s مرفق/مرفقات مُرسلة.",
    "Campaign": "حملة",
    "Campaign \"%(name)s\" already has an active execution (attempt %(attempt)s). Wait for it to finish or reconcile stale runs before starting again.": "الحملة \"%(name)s\" لديها تنفيذ نشط (محاولة %(attempt)s). انتظر حتى ينتهي أو أعد موازنة التشغيلات المتوقفة قبل البدء مجددًا.",
    "Campaign Monitor": "مراقبة الحملات",
    "Campaign Performance": "أداء الحملة",
    "Campaign Pivot": "محور الحملة",
    "Campaign Summary": "ملخص الحملة",
    "Can send WhatsApp messages and view message logs.": "يمكنه إرسال رسائل واتساب وعرض سجل الرسائل.",
    "Cancel": "إلغاء",
    "Cancelled": "ملغى",
    "Cannot retry while the campaign is still running.": "لا يمكن إعادة المحاولة بينما الحملة لا تزال قيد التشغيل.",
    "Cannot start an empty campaign. Add a message, attachments, or products.": "لا يمكن بدء حملة فارغة. أضف رسالة أو مرفقات أو منتجات.",
    "Capabilities": "القدرات",
    "Catalog": "كتالوج",
    "Close": "إغلاق",
    "Common": "عام",
    "Company": "الشركة",
    "Completed": "مكتمل",
    "Completed Today": "اكتمل اليوم",
    "Completed with Errors": "اكتمل مع أخطاء",
    "Configuration name": "اسم الإعداد",
    "Configure your WhatsApp provider": "قم بإعداد مزود واتساب",
    "Connection Successful": "الاتصال ناجح",
    "Connection test failed: %s": "فشل اختبار الاتصال: %s",
    "Contact": "جهة اتصال",
    "Contact us for ordering.": "تواصلوا معنا للطلب.",
    "Cooldown Duration (seconds)": "مدة فترة التهدئة (ثوانٍ)",
    "Cooldown Every N Messages": "فترة تهدئة كل N رسالة",
    "Cooldown duration cannot be negative.": "لا يمكن أن تكون مدة فترة التهدئة سالبة.",
    "Cooldown message count cannot be negative.": "لا يمكن أن يكون عدد رسائل فترة التهدئة سالبًا.",
    "Cooldowns": "فترات التهدئة",
    "Counters": "العدادات",
    "Create Sale Order": "إنشاء أمر بيع",
    "Create Sale Order from Selection": "إنشاء أمر بيع من الاختيار",
    "Created by": "أُنشئ بواسطة",
    "Created on": "تاريخ الإنشاء",
    "Credentials": "بيانات الاعتماد",
    "Current Contact": "جهة الاتصال الحالية",
    "Current Number": "الرقم الحالي",
    "Current Product": "المنتج الحالي",
    "Current Recipient": "المستلم الحالي",
    "Current Step": "الخطوة الحالية",
    "Customer": "العميل",
    "Customer selection notes...": "ملاحظات اختيار العميل...",
    "Daily Send Limit": "حد الإرسال اليومي",
    "Daily WhatsApp send limit reached (%(limit)s). Already sent today: %(sent)s. Reduce recipients or increase the limit in WhatsApp Settings.": "تم بلوغ حد الإرسال اليومي لواتساب (%(limit)s). المُرسل اليوم: %(sent)s. قلّل المستلمين أو زِد الحد في إعدادات واتساب.",
    "Daily send limit cannot be negative.": "لا يمكن أن يكون حد الإرسال اليومي سالبًا.",
    "Date": "التاريخ",
    "Dedicated WhatsApp Log File": "ملف سجل واتساب مخصص",
    "Degraded": "متدهور",
    "Delay values cannot be negative.": "لا يمكن أن تكون قيم التأخير سالبة.",
    "Delivered": "تم التسليم",
    "Delivery Analysis": "تحليل التسليم",
    "Delivery Dashboard": "لوحة التسليم",
    "Delivery Overview": "نظرة عامة على التسليم",
    "Delivery Pivot": "محور التسليم",
    "Delivery State": "حالة التسليم",
    "Deterministic test numbers": "أرقام اختبار حتمية",
    "Disconnected": "غير متصل",
    "Display Name": "الاسم المعروض",
    "Done": "منتهٍ",
    "Draft": "مسودة",
    "Duplicate phone numbers in recipient list: %s": "أرقام هواتف مكررة في قائمة المستلمين: %s",
    "Duration (seconds)": "المدة (ثوانٍ)",
    "Elapsed": "منقضٍ",
    "Enter a message, attach files, or select products.": "أدخل رسالة أو أرفق ملفات أو اختر منتجات.",
    "Error Message": "رسالة الخطأ",
    "Execution Attempt": "محاولة تنفيذ",
    "Execution Attempts": "محاولات التنفيذ",
    "Executions": "التنفيذات",
    "Failed": "فشل",
    "Failed At": "وقت الفشل",
    "Failed Logs": "سجلات الفاشلة",
    "Failed to send WhatsApp message. %s": "فشل إرسال رسالة واتساب. %s",
    "Failure": "الفشل",
    "Failure Rate %": "نسبة الفشل %",
    "Failure Reason": "سبب الفشل",
    "File \"%s\"": "ملف \"%s\"",
    "Files (%(count)s): %(names)s": "ملفات (%(count)s): %(names)s",
    "Finished": "انتهى",
    "Finished At": "وقت الانتهاء",
    "Full access to WhatsApp settings and message logs.": "وصول كامل إلى إعدادات واتساب وسجل الرسائل.",
    "Health": "الصحة",
    "Healthy": "سليم",
    "ID": "المعرّف",
    "Include Product Description": "تضمين وصف المنتج",
    "Included Descriptions": "الأوصاف المضمّنة",
    "Initial": "أولي",
    "International format recommended, e.g. +20 10 1234 5678": "يُفضّل الصيغة الدولية، مثل +20 10 1234 5678",
    "Invalid WhatsApp provider configuration: %s": "إعداد مزود واتساب غير صالح: %s",
    "Invalid attachment data.": "بيانات المرفق غير صالحة.",
    "Invalid provider type: %(type)s": "نوع مزود غير صالح: %(type)s",
    "Last Activity": "آخر نشاط",
    "Last Error": "آخر خطأ",
    "Last Failed Connection": "آخر اتصال فاشل",
    "Last Latency (ms)": "آخر زمن استجابة (ms)",
    "Last Successful Connection": "آخر اتصال ناجح",
    "Last Updated by": "آخر تحديث بواسطة",
    "Last Updated on": "تاريخ آخر تحديث",
    "Live Processing": "المعالجة المباشرة",
    "Live Progress": "التقدم المباشر",
    "Manager": "مدير",
    "Max Attachment Size (MB)": "الحد الأقصى لحجم المرفق (MB)",
    "Max Attachments per Message": "الحد الأقصى للمرفقات لكل رسالة",
    "Max Delay (seconds)": "أقصى تأخير (ثوانٍ)",
    "Max attachment size must be greater than zero.": "يجب أن يكون الحد الأقصى لحجم المرفق أكبر من صفر.",
    "Max attachments cannot be negative.": "لا يمكن أن يكون الحد الأقصى للمرفقات سالبًا.",
    "Max delay must be greater than or equal to min delay.": "يجب أن يكون أقصى تأخير أكبر من أو يساوي أدنى تأخير.",
    "Message": "الرسالة",
    "Message Log": "سجل رسالة",
    "Message Logs": "سجل الرسائل",
    "Message Sent": "تم إرسال الرسالة",
    "Min Delay (seconds)": "أدنى تأخير (ثوانٍ)",
    "Mock Provider Ready": "مزود الاختبار جاهز",
    "Mock Provider active.": "مزود الاختبار نشط.",
    "Mock Simulation": "محاكاة الاختبار",
    "Name": "الاسم",
    "New Products Available:": "منتجات جديدة متوفرة:",
    "No active WhatsApp configuration found. Please configure WhatsApp in Settings.": "لم يُعثر على إعداد واتساب نشط. يُرجى الإعداد من قائمة الإعدادات.",
    "No active campaigns": "لا توجد حملات نشطة",
    "No failed or skipped recipients to retry for this campaign.": "لا يوجد مستلمون فاشلون أو متخطّون لإعادة المحاولة في هذه الحملة.",
    "No phone fields are available on contacts. Cannot send WhatsApp messages.": "لا توجد حقول هاتف على جهات الاتصال. لا يمكن إرسال رسائل واتساب.",
    "No product images available to send. Add images or turn off \"Use Product Images\".": "لا توجد صور منتجات للإرسال. أضف صورًا أو عطّل \"استخدام صور المنتجات\".",
    "No real WhatsApp messages are sent. Use for QA, demos, and stress tests only.": "لن تُرسل رسائل واتساب حقيقية. للاختبار والعروض التوضيحية واختبارات الضغط فقط.",
    "No valid phone number is available on this contact. Please set a %s number.": "لا يوجد رقم هاتف صالح على جهة الاتصال هذه. يُرجى تعيين رقم %s.",
    "No valid phone number on this contact.": "لا يوجد رقم هاتف صالح على جهة الاتصال هذه.",
    "None of the selected contacts have a valid phone number.": "لا تملك أي جهة اتصال محددة رقم هاتف صالح.",
    "Notes": "ملاحظات",
    "Observability": "المراقبة (Observability)",
    "Only one active WhatsApp configuration is allowed per company.": "يُسمح بإعداد واتساب نشط واحد فقط لكل شركة.",
    "Open Monitor": "فتح المراقبة",
    "Outcome Rates (weighted random)": "معدلات النتائج (عشوائي موزّن)",
    "Parent Campaign": "الحملة الأم",
    "Pending": "في الانتظار",
    "Performance": "الأداء",
    "Please enter a message or attach a file.": "يُرجى إدخال رسالة أو إرفاق ملف.",
    "Please select a customer.": "يُرجى اختيار عميل.",
    "Please select at least one contact.": "يُرجى اختيار جهة اتصال واحدة على الأقل.",
    "Please select at least one product.": "يُرجى اختيار منتج واحد على الأقل.",
    "Please set a customer on this sales order before sending WhatsApp.": "يُرجى تعيين عميل على أمر البيع قبل إرسال واتساب.",
    "Preparing recipient": "تحضير المستلم",
    "Preview": "معاينة",
    "Processed": "مُعالَج",
    "Product": "منتج",
    "Product \"%s\"": "منتج \"%s\"",
    "Product Catalog: %s": "كتالوج المنتجات: %s",
    "Product Preview": "معاينة المنتجات",
    "Product image \"%(name)s\" is too large (%(size).2f MB). Maximum allowed: %(max)s MB.": "صورة المنتج \"%(name)s\" كبيرة جدًا (%(size).2f MB). الحد الأقصى: %(max)s MB.",
    "Product images: %s": "صور المنتجات: %s",
    "Products": "المنتجات",
    "Progress": "التقدم",
    "Progress %": "التقدم %",
    "Progress Summary": "ملخص التقدم",
    "Provider": "مزود",
    "Provider \"%(provider)s\" is not implemented yet. Select Green API or add a custom adapter.": "المزود \"%(provider)s\" غير مُنفّذ بعد. اختر Green API أو أضف محولًا مخصصًا.",
    "Provider \"%s\" is not implemented yet.": "المزود \"%s\" غير مُنفّذ بعد.",
    "Provider %(provider)s is working. State: %(state)s": "المزود %(provider)s يعمل. الحالة: %(state)s",
    "Provider Self-Test": "اختبار ذاتي للمزود",
    "Provider Status": "حالة المزود",
    "Provider Type": "نوع المزود",
    "Provider-Specific": "خاص بالمزود",
    "Quantity": "الكمية",
    "Queued": "في الانتظار",
    "Queued / Sending": "في الانتظار / جاري الإرسال",
    "Rate Limit Rate %": "نسبة حد المعدّل %",
    "Recipient": "مستلم",
    "Recipient Number": "رقم المستلم",
    "Recipient phone number is invalid or malformed.": "رقم هاتف المستلم غير صالح أو بصيغة خاطئة.",
    "Recipient phone number is invalid.": "رقم هاتف المستلم غير صالح.",
    "Recipient phone number is required.": "رقم هاتف المستلم مطلوب.",
    "Recipients": "المستلمون",
    "Recovered after interrupted execution": "تم الاسترداد بعد تنفيذ متوقف",
    "Reference": "المرجع",
    "Remaining": "متبقٍ",
    "Retry": "إعادة محاولة",
    "Retry Campaign": "حملة إعادة محاولة",
    "Retry Campaigns": "حملات إعادة المحاولة",
    "Retry Count": "عدد إعادات المحاولة",
    "Retry Failed Recipients": "إعادة المحاولة للمستلمين الفاشلين",
    "Retry: %s": "إعادة محاولة: %s",
    "Running": "قيد التشغيل",
    "Running Duration (s)": "مدة التشغيل (ث)",
    "Running bulk sends appear here with live progress. This view refreshes every few seconds.": "تظهر هنا الإرسالات الجماعية الجارية مع التقدم المباشر. تُحدَّث هذه الشاشة كل بضع ثوانٍ.",
    "Safety": "السلامة",
    "Sale Order": "أمر بيع",
    "Sale Order Count": "عدد أوامر البيع",
    "Sales Order": "أمر بيع",
    "Sales Orders": "أوامر البيع",
    "Select <strong>Green API</strong> for production or\n                <strong>Mock Provider</strong> for safe testing without sending real messages.": "اختر <strong>Green API</strong> للإنتاج أو\n                <strong>Mock Provider</strong> للاختبار الآمن دون إرسال رسائل حقيقية.",
    "Select at least one contact to send WhatsApp messages.": "اختر جهة اتصال واحدة على الأقل لإرسال رسائل واتساب.",
    "Select multiple files. Each file is sent in order with a short delay. Product catalog images stay on the Products tab and are never mixed with these uploads.": "اختر ملفات متعددة. يُرسل كل ملف بالترتيب مع تأخير قصير. صور كتالوج المنتجات تبقى في تبويب المنتجات ولا تُختلط مع هذه المرفوعات.",
    "Selected Products": "المنتجات المختارة",
    "Selected products have no images. Disable \"Use Product Images\" or add images.": "المنتجات المحددة بلا صور. عطّل \"استخدام صور المنتجات\" أو أضف صورًا.",
    "Send": "إرسال",
    "Send WhatsApp": "إرسال واتساب",
    "Send WhatsApp (Bulk)": "إرسال واتساب (جماعي)",
    "Send WhatsApp Message": "إرسال رسالة واتساب",
    "Send each product image with caption after the catalog message.": "أرسل كل صورة منتج مع تعليق بعد رسالة الكتالوج.",
    "Sending": "جاري الإرسال",
    "Sending attachment %s/%s": "إرسال مرفق %s/%s",
    "Sending message": "إرسال الرسالة",
    "Sending product image %s/%s": "إرسال صورة منتج %s/%s",
    "Sending to recipient": "الإرسال إلى المستلم",
    "Sent": "مُرسل",
    "Sent At": "وقت الإرسال",
    "Sent By": "أُرسل بواسطة",
    "Sent Date": "تاريخ الإرسال",
    "Sent Logs": "سجلات المرسلة",
    "Settings": "الإعدادات",
    "Simulated Latency (ms)": "زمن الاستجابة المحاكى (ms)",
    "Simulated latency cannot be negative.": "لا يمكن أن يكون زمن الاستجابة المحاكى سالبًا.",
    "Skipped": "تم تخطيه",
    "Skipped Logs": "سجلات المتخطاة",
    "Started At": "وقت البدء",
    "Starting campaign": "بدء الحملة",
    "Statistics": "الإحصائيات",
    "Status": "الحالة",
    "Stopped": "متوقف",
    "Success Rate": "معدل النجاح",
    "Success Rate %": "معدل النجاح %",
    "Success: %(rate)s%%": "النجاح: %(rate)s%%",
    "TEST MODE - NO REAL MESSAGES": "وضع الاختبار — لا رسائل حقيقية",
    "TEST MODE — no real WhatsApp messages will be sent. State: %(state)s": "وضع الاختبار — لن تُرسل رسائل واتساب حقيقية. الحالة: %(state)s",
    "Test Connection": "اختبار الاتصال",
    "Test Mode": "وضع الاختبار",
    "Test Mode Alert Body": "نص تنبيه وضع الاختبار",
    "Test Mode Alert Title": "عنوان تنبيه وضع الاختبار",
    "Text": "نص",
    "Timeout Rate %": "نسبة انتهاء المهلة %",
    "Today": "اليوم",
    "Too many free attachments (%(count)s). Maximum allowed: %(max)s.": "مرفقات مرفوعة كثيرة (%(count)s). الحد الأقصى: %(max)s.",
    "Total": "الإجمالي",
    "Total Attachments": "إجمالي المرفقات",
    "Total Failed": "إجمالي الفاشل",
    "Total Processed": "إجمالي المُعالَج",
    "Total Recipients": "إجمالي المستلمين",
    "Total Sent": "إجمالي المُرسل",
    "Total Skipped": "إجمالي المتخطى",
    "Total size of free attachments (%.2f MB) exceeds the maximum allowed: %s MB.": "الحجم الإجمالي للمرفقات المرفوعة (%.2f MB) يتجاوز الحد الأقصى: %s MB.",
    "Type your message or select products to auto-generate...": "اكتب رسالتك أو اختر منتجات للتوليد التلقائي...",
    "Type your message...": "اكتب رسالتك...",
    "Unknown WhatsApp provider type: %s": "نوع مزود واتساب غير معروف: %s",
    "Unknown error": "خطأ غير معروف",
    "Use Product Images": "استخدام صور المنتجات",
    "Used Product Images": "صور منتجات مستخدمة",
    "User": "مستخدم",
    "User-uploaded files for this campaign (not product catalog images).": "ملفات مرفوعة من المستخدم لهذه الحملة (ليست صور كتالوج المنتجات).",
    "View Logs": "عرض السجلات",
    "WhatsApp": "واتساب",
    "WhatsApp Bulk Campaign": "حملة واتساب جماعية",
    "WhatsApp Bulk Send": "إرسال واتساب جماعي",
    "WhatsApp Campaign": "حملة واتساب",
    "WhatsApp Campaign %s": "حملة واتساب %s",
    "WhatsApp Configuration": "إعداد واتساب",
    "WhatsApp Log": "سجل واتساب",
    "WhatsApp Message Log": "سجل رسائل واتساب",
    "WhatsApp Product Selection": "اختيار منتجات واتساب",
    "WhatsApp Settings": "إعدادات واتساب",
    "WhatsApp integration is disabled. Enable it in Settings.": "تكامل واتساب معطّل. فعّله من الإعدادات.",
    "WhatsApp message was sent successfully.": "تم إرسال رسالة واتساب بنجاح.",
    "WhatsApp messaging integration": "تكامل رسائل واتساب",
    "WhatsApp provider \"%s\" is not implemented yet. Please select Green API or implement adapter %s.": "مزود واتساب \"%s\" غير مُنفّذ بعد. اختر Green API أو نفّذ المحول %s.",
    "With Errors": "مع أخطاء",
    "Wizard": "معالج",
    "e.g. +1 555 123 4567": "مثال: +1 555 123 4567",
    "elapsed": "منقضٍ",
    "mobile": "جوال",
    "phone": "هاتف",
    "API URL is required for Green API.": "API URL مطلوب لـ Green API.",
    "Access Token is required for Green API.": "Access Token مطلوب لـ Green API.",
    "Instance ID is required for Green API.": "Instance ID مطلوب لـ Green API.",
}

def should_keep_english(msgid: str) -> bool:
    if msgid in KEEP_ENGLISH:
        return True
    if msgid in {"Send WhatsApp Bulk Wizard", "Send WhatsApp Message Wizard"}:
        return True
    return False


def main() -> None:
    pot = polib.pofile(str(POT))
    po = polib.POFile()
    po.metadata = dict(pot.metadata)
    po.metadata.update(
        {
            "Language": "ar",
            "Language-Team": "RelayRuntime Arabic",
            "Plural-Forms": "nplurals=6; plural=n==0 ? 0 : n==1 ? 1 : n==2 ? 2 : n%100>=3 && n%100<=10 ? 3 : n%100>=11 ? 4 : 5;",
            "PO-Revision-Date": pot.metadata.get("POT-Creation-Date", ""),
        }
    )

    translated = skipped = missing = 0
    for entry in pot:
        msgid = entry.msgid
        if not msgid:
            po.append(entry)
            continue
        new = polib.POEntry(
            msgid=entry.msgid,
            msgstr="",
            occurrences=entry.occurrences,
            comment=entry.comment,
            tcomment=entry.tcomment,
            flags=entry.flags,
        )
        if should_keep_english(msgid):
            skipped += 1
            if msgid in {
                "Execution UUID",
                "Idempotency Key",
                "Reconciled",
            }:
                new.tcomment = "runtime: keep English label per LOCALIZATION_PLAN"
        elif msgid in TRANSLATIONS:
            new.msgstr = TRANSLATIONS[msgid]
            translated += 1
            if msgid in {"Provider", "Provider Status", "Observability", "Execution Attempt"}:
                new.tcomment = "hybrid UX: Arabic label; technical token stays Latin in help/value"
        else:
            missing += 1
            new.tcomment = "Phase 3: review — no Arabic mapping yet; falls back to English"
        po.append(new)

    po.save(str(PO))
    print(f"Wrote {PO}")
    print(f"entries={len(pot)} translated={translated} keep_english={skipped} missing={missing}")


if __name__ == "__main__":
    main()
